### ISSUE TITLE
feature: que el simulador escriba un archivo con los puntos de ignicion generados

### ISSUE THREAD

**Issue by fdobad** [fire2a/C2FSB#5]
Actualmente se leen de esta linea:

```
Selected (Random) ignition point for Year 1, sim 1: 284298
----------------------------- Results -----------------------------
Total Available Cells:    232397 - % of the Forest: 74.9958%
Total Burnt Cells:        225 - % of the Forest: 0.0726088%
Total Non-Burnable Cells: 77258 - % of the Forest: 24.9316%
Total Harvested Cells: 0 - % of the Forest: 0%
```

Pero es razonable escribirlos en un archivo aparte como expost ignitions.csv

## jeje
```
In [110]: with open('LogFile.txt', 'r') as afile:
     ...:     igPoints = re.findall( 'ignition point for Year [0-9]*, sim [0-9]*: ([0-9]+)', afile.read())
     ...:     igPoints = list(map(int, igPoints))
     ...: print(igPoints)
     ...:
     ...:
[280059, 666]
```

Listo, está en stats.py, al añadirle la bandera --stats se debería generar. pfv probar

**Comment by fdobad** [comment]
En todo caso lo estoy leyendo del logfile exitosamente, o sea, baja prioridad.
Probé la bandera stats, me tira esto:
```
General stats...

!@#$%^&* stdError stream:
Traceback (most recent call last):
  File "/home/fdo/dev/C2FSB/main.py", line 35, in <module>
    main()    
  File "/home/fdo/dev/C2FSB/main.py", line 28, in main
    env.stats()
  File "/home/fdo/dev/C2FSB/Cell2FireC.py", line 292, in stats

!@#$%^&* stdError stream:
    StatsPrinter.GeneralStats()
  File "/home/fdo/dev/C2FSB/Cell2Fire/Stats.py", line 1025, in GeneralStats
    self.OutfileIgnitions()
  File "/home/fdo/dev/C2FSB/Cell2Fire/Stats.py", line 1008, in OutfileIgnitions
    list_of_values,simulations=ReadLogfile(self._OutFolder, "sim")
NameError: name 'ReadLogfile' is not defined


--nthreads 2 --max-fire-periods 72 --nsims 10 --ROS-CV 1.0 --scenario 2 --weather random --final-grid --stats --input-instance-folder /home/fdo/dev/C2FSB/data/Vilopriu_2013/Instance23-03-09_22-36-10/ --output-folder /home/fdo/dev/C2FSB/data/Vilopriu_2013/Instance23-03-09_22-36-10/results 
```

**Comment by fire2a** [comment]
Done

**Comment by fire2a** [comment]
Solved
