### ISSUE TITLE
Generating Data.csv File... se cuelga con instancia grande (propuesta escribir linea por linea sin cargar todo a memoria y despues a dataframe.writecsv)

### ISSUE THREAD

**Issue by fdobad** [fire2a/C2FSB#6]
```
Starting run process --max-fire-periods 72 --grids --input-instance-folder /home/fdo/Downloads/test/Instance23-03-11_19-47-04/ --output-folder /home/fdo/Downloads/test/Instance23-03-11_19-47-04/results 
workdir /home/fdo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/fire2am/C2FSB
args ['python3', 'main.py', '--max-fire-periods', '72', '--grids', '--input-instance-folder', '/home/fdo/Downloads/test/Instance23-03-11_19-47-04/', '--output-folder', '/home/fdo/Downloads/test/Instance23-03-11_19-47-04/results']
State changed: Starting
Started
State changed: Running
Generating Data.csv File...

!@#$%^&* stdError stream:
Traceback (most recent call last):
  File "/home/fdo/dev/C2FSB/main.py", line 35, in <module>

!@#$%^&* stdError stream:
    main()    
  File "/home/fdo/dev/C2FSB/main.py", line 23, in main
    env = Cell2FireC(args)
  File "/home/fdo/dev/C2FSB/Cell2FireC.py", line 26, in __init__
    self.generateDataC()
  File "/home/fdo/dev/C2FSB/Cell2FireC.py", line 178, in generateDataC
    DataGenerator.GenDataFile(self.args.InFolder)
  File "/home/fdo/dev/C2FSB/Cell2Fire/DataGeneratorC.py", line 216, in GenDataFile
    Elevation, SAZ, PS, Curing, CBD, CBH, CCF,PY,FMC = DataGrids(InFolder, NCells)
  File "/home/fdo/dev/C2FSB/Cell2Fire/DataGeneratorC.py", line 145, in DataGrids
    Elevation[aux] = float(c)
IndexError: index 3564288 is out of bounds for axis 0 with size 3564288
```

**Comment by fdobad** [comment]
```
    DF["lat"] = np.zeros(len(GFuelType)) + 51.621244
    DF["lon"] = np.zeros(len(GFuelType)).astype(int) - 115.608378
```
¿Por qué no se puede quitar esta parte?

**Comment by fire2a** [comment]
Cargar cada archivo individual?

**Comment by fire2a** [comment]
Parquet for output?
