### ISSUE TITLE
output geotiff indent error

### ISSUE THREAD

**Issue by fdobad** [fire2a/C2FSB#7]
```
Traceback (most recent call last):
  File "/home/fdo/dev/fire2am/C2FSB/main.py", line 14, in <module>
    from Cell2FireC import *
  File "/home/fdo/dev/fire2am/C2FSB/Cell2FireC.py", line 109
    OutputGeotiff(self.args.InFolder,self.args.OutFolder,self.args.nsims)
                                                                         ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by fire2a** [comment]
Solved
